#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU
configuration: Release

build_script:
  - ps: build.ps1 --target=build

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - ps: build.ps1 --target=run-tests
build_success:
  - ps: build.ps1 --target=package


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: 'Publish\**'

#---------------------------------#
#        global handlers          #
#---------------------------------#
on_success:
  - ps: Write-Host 'Succesfuly build'