#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU
configuration: Release

before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1 --target=build

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - ps: .\build.ps1 --target=run-tests
after_test:
  - ps: .\build.ps1 --target=package


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: 'Publish\**'

#---------------------------------#
#        global handlers          #
#---------------------------------#
on_success:
  - ps: Write-Host 'Succesfuly build'